### PR TITLE
Adventures in reviewing PR #8

### PR DESCRIPTION
**Pull request by erights**
My adventures in trying to run PR #8 to help review it. Running `agoric install` produced the changes in this PR. But `yarn build` followed by `yarn test` produced the following two errors. How do I run the `pegasus-new-zoe` branch successfully?

```
$ yarn test
yarn run v1.22.4
$ yarn workspaces run test

> dapp-peg-api
$ tape -r esm 'test/**/*.js'

> dapp-peg-contract
$ tape -r esm 'test/**/test-*.js' | tap-spec

  remote peg

    ✔ got the deposit-only facet
    ✔ Gaia sent the atoms
    ✔ we received the shadow atoms
    ✔ alleged peg name is equal

    ✖ unexpected exception
    -----------------------
      operator: notEqual
      expected: |-
        [TypeError: prototype [Alleged: Local1 brand] of unknown.give.Transfer.brand is not already in the fringeSet]
      actual: |-
        [TypeError: prototype [Alleged: Local1 brand] of unknown.give.Transfer.brand is not already in the fringeSet]
      stack: |-
  TypeError: prototype [Alleged: Local1 brand] of unknown.give.Transfer.brand is not already in the fringeSet
  at /Users/markmiller/src/ongithub/agoric/dapp-pegasus/contract/node_modules/@agoric/harden/dist/harden.cjs.js:112:17
  at Map.forEach (<anonymous>)
  at checkPrototypes (/Users/markmiller/src/ongithub/agoric/dapp-pegasus/contract/node_modules/@agoric/harden/dist/harden.cjs.js:109:18)
  at harden (/Users/markmiller/src/ongithub/agoric/dapp-pegasus/contract/node_modules/@agoric/harden/dist/harden.cjs.js:132:5)
  at testRemotePeg (/Users/markmiller/src/ongithub/agoric/dapp-pegasus/contract/test/test-peg.js:128:5)


    ✖ plan != count
    ----------------
      operator: fail
      expected: 8
      actual:   5
      at: process.<anonymous> (/Users/markmiller/src/ongithub/agoric/dapp-pegasus/node_modules/tape/index.js:83:19)
      stack: |-
  Error: plan != count
  at Test.assert [as _assert] (/Users/markmiller/src/ongithub/agoric/dapp-pegasus/node_modules/tape/lib/test.js:228:54)
  at Test.bound [as _assert] (/Users/markmiller/src/ongithub/agoric/dapp-pegasus/node_modules/tape/lib/test.js:80:32)
  at Test.fail (/Users/markmiller/src/ongithub/agoric/dapp-pegasus/node_modules/tape/lib/test.js:322:10)
  at Test.bound [as fail] (/Users/markmiller/src/ongithub/agoric/dapp-pegasus/node_modules/tape/lib/test.js:80:32)
  at Test._exit (/Users/markmiller/src/ongithub/agoric/dapp-pegasus/node_modules/tape/lib/test.js:185:14)
  at Test.bound [as _exit] (/Users/markmiller/src/ongithub/agoric/dapp-pegasus/node_modules/tape/lib/test.js:80:32)
  at process.<anonymous> (/Users/markmiller/src/ongithub/agoric/dapp-pegasus/node_modules/tape/index.js:83:19)
  at process.emit (events.js:327:22)
  at process.EventEmitter.emit (domain.js:485:12)
  at process.topLevelDomainCallback (domain.js:137:15)
```

### CODE REVIEW

**Comment by erights** [comment]
Just looked at the contents of this PR. It is extremely wrong. Far fewer files were affected by running `agoric install`. I don't know what's going on here, but I probably misunderstood something about git or GitHub.

**Comment by erights** [comment]
> Just looked at the contents of this PR. It is extremely wrong. Far fewer files were affected by running `agoric install`. I don't know what's going on here, but I probably misunderstood something about git or GitHub.

Nevermind. The explosion of files is in `_agstate` which I probably should not have checked in anyway.

**Comment by michaelfig** [comment]
The error looks like a mistake in `@agoric/marshal`, where the hardening is not happening in the correct order.

**Comment by michaelfig** [comment]
Actually, I've just now updated `pegasus-new-zoe` to remove references to `@agoric/harden` and that seemed to do the trick.  Closing.

**Pull request closed without merging**
